
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM__FROM_CART";
export const INCREMENT_CART_PROD = "INCREMENT_CART_PROD";
export const DECREMENT_CART_PROD = "DECREMENT_CART_PROD";
export const CART_LOADING = "CART_LOADING";
export const CART_EMPTY = "CART_EMPTY"